version: '3.8'

services:
  
  # php Service
  php:
    container_name: php
    build:
      context: .
      target: php
      working_dir: /var/www
      volumes:
        - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - database

  # Database Service
  database:
    container_name: database
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: ~